export type DocumentStatus =
  "Recebido" | "Pendente" | "Em análise" | "Aprovado" | "Rejeitado" | "Vencendo" | "Vencido";
export type DocumentUnit = "Carapicuíba" | "Jardim D'Abril" | "Jardim Conceição";

export type ProcessDocument = {
  id: string;
  process_id: string;
  client_id: string;
  vehicle_id?: string;
  unit_id: DocumentUnit;
  client: string;
  process: string;
  process_type: string;
  vehicle?: string;
  document_type: string;
  file_name: string;
  file_type: "PDF" | "JPG" | "PNG";
  file_size: string;
  status: DocumentStatus;
  received_at?: string;
  expires_at?: string;
  reviewed_by?: string;
  reviewed_at?: string;
  notes?: string;
  version: number;
};

export const currentMockDate = "24/09/2026";

export const documentMocks: ProcessDocument[] = [
  {
    id: "doc-001",
    process_id: "DHG-00124",
    client_id: "cli-001",
    vehicle_id: "veh-001",
    unit_id: "Carapicuíba",
    client: "João da Silva",
    process: "#DHG-00124",
    process_type: "Transferência de propriedade",
    vehicle: "Honda Civic - ABC1D23",
    document_type: "CNH",
    file_name: "cnh-joao-silva.pdf",
    file_type: "PDF",
    file_size: "1,8 MB",
    status: "Aprovado",
    received_at: "20/09/2026",
    reviewed_by: "Renata Oliveira",
    reviewed_at: "21/09/2026",
    notes: "Documento conferido e aprovado.",
    version: 1,
  },
  {
    id: "doc-002",
    process_id: "DHG-00124",
    client_id: "cli-001",
    vehicle_id: "veh-001",
    unit_id: "Carapicuíba",
    client: "João da Silva",
    process: "#DHG-00124",
    process_type: "Transferência de propriedade",
    vehicle: "Honda Civic - ABC1D23",
    document_type: "CRLV",
    file_name: "crlv-abc1d23.pdf",
    file_type: "PDF",
    file_size: "2,1 MB",
    status: "Aprovado",
    received_at: "20/09/2026",
    reviewed_by: "Renata Oliveira",
    reviewed_at: "21/09/2026",
    version: 2,
  },
  {
    id: "doc-003",
    process_id: "DHG-00124",
    client_id: "cli-001",
    vehicle_id: "veh-001",
    unit_id: "Carapicuíba",
    client: "João da Silva",
    process: "#DHG-00124",
    process_type: "Transferência de propriedade",
    vehicle: "Honda Civic - ABC1D23",
    document_type: "Comprovante de residência",
    file_name: "residencia-joao.jpg",
    file_type: "JPG",
    file_size: "860 KB",
    status: "Aprovado",
    received_at: "19/09/2026",
    reviewed_by: "Renata Oliveira",
    reviewed_at: "20/09/2026",
    version: 1,
  },
  {
    id: "doc-004",
    process_id: "DHG-00124",
    client_id: "cli-001",
    vehicle_id: "veh-001",
    unit_id: "Carapicuíba",
    client: "João da Silva",
    process: "#DHG-00124",
    process_type: "Transferência de propriedade",
    vehicle: "Honda Civic - ABC1D23",
    document_type: "CRV/ATPV-e",
    file_name: "atpve-joao-silva.pdf",
    file_type: "PDF",
    file_size: "1,2 MB",
    status: "Pendente",
    notes: "Aguardando assinatura do vendedor.",
    version: 0,
  },
  {
    id: "doc-005",
    process_id: "DHG-00124",
    client_id: "cli-001",
    vehicle_id: "veh-001",
    unit_id: "Carapicuíba",
    client: "João da Silva",
    process: "#DHG-00124",
    process_type: "Transferência de propriedade",
    vehicle: "Honda Civic - ABC1D23",
    document_type: "Procuração",
    file_name: "procuracao-joao.pdf",
    file_type: "PDF",
    file_size: "720 KB",
    status: "Vencendo",
    received_at: "18/09/2026",
    expires_at: "29/09/2026",
    reviewed_by: "Renata Oliveira",
    reviewed_at: "19/09/2026",
    notes: "Renovar antes do protocolo final.",
    version: 1,
  },
  {
    id: "doc-006",
    process_id: "DHG-00131",
    client_id: "cli-002",
    vehicle_id: "veh-002",
    unit_id: "Carapicuíba",
    client: "Marina Torres",
    process: "#DHG-00131",
    process_type: "Licenciamento",
    vehicle: "Fiat Argo - DEF4G56",
    document_type: "CRLV",
    file_name: "crlv-def4g56.pdf",
    file_type: "PDF",
    file_size: "1,5 MB",
    status: "Em análise",
    received_at: "23/09/2026",
    version: 1,
  },
  {
    id: "doc-007",
    process_id: "DHG-00131",
    client_id: "cli-002",
    vehicle_id: "veh-002",
    unit_id: "Carapicuíba",
    client: "Marina Torres",
    process: "#DHG-00131",
    process_type: "Licenciamento",
    vehicle: "Fiat Argo - DEF4G56",
    document_type: "CPF",
    file_name: "cpf-marina.png",
    file_type: "PNG",
    file_size: "420 KB",
    status: "Recebido",
    received_at: "23/09/2026",
    version: 1,
  },
  {
    id: "doc-008",
    process_id: "DHG-00138",
    client_id: "cli-003",
    vehicle_id: "veh-003",
    unit_id: "Jardim D'Abril",
    client: "Empresa Aurora Ltda.",
    process: "#DHG-00138",
    process_type: "Débitos e Regularizações",
    vehicle: "VW Saveiro - HIJ7K89",
    document_type: "Documento empresarial",
    file_name: "contrato-social-aurora.pdf",
    file_type: "PDF",
    file_size: "3,4 MB",
    status: "Aprovado",
    received_at: "17/09/2026",
    reviewed_by: "Felipe Nunes",
    reviewed_at: "18/09/2026",
    version: 1,
  },
  {
    id: "doc-009",
    process_id: "DHG-00138",
    client_id: "cli-003",
    vehicle_id: "veh-003",
    unit_id: "Jardim D'Abril",
    client: "Empresa Aurora Ltda.",
    process: "#DHG-00138",
    process_type: "Débitos e Regularizações",
    vehicle: "VW Saveiro - HIJ7K89",
    document_type: "Procuração",
    file_name: "procuracao-aurora.pdf",
    file_type: "PDF",
    file_size: "940 KB",
    status: "Vencido",
    received_at: "05/09/2026",
    expires_at: "21/09/2026",
    reviewed_by: "Felipe Nunes",
    reviewed_at: "06/09/2026",
    notes: "Solicitar procuração atualizada.",
    version: 1,
  },
  {
    id: "doc-010",
    process_id: "DHG-00138",
    client_id: "cli-003",
    vehicle_id: "veh-003",
    unit_id: "Jardim D'Abril",
    client: "Empresa Aurora Ltda.",
    process: "#DHG-00138",
    process_type: "Débitos e Regularizações",
    vehicle: "VW Saveiro - HIJ7K89",
    document_type: "Contrato",
    file_name: "contrato-servicos-aurora.pdf",
    file_type: "PDF",
    file_size: "2,6 MB",
    status: "Rejeitado",
    received_at: "22/09/2026",
    reviewed_by: "Felipe Nunes",
    reviewed_at: "23/09/2026",
    notes: "Arquivo sem assinatura das partes.",
    version: 1,
  },
  {
    id: "doc-011",
    process_id: "DHG-00142",
    client_id: "cli-004",
    unit_id: "Jardim D'Abril",
    client: "Beatriz Cardoso",
    process: "#DHG-00142",
    process_type: "CNH",
    document_type: "RG",
    file_name: "rg-beatriz.jpg",
    file_type: "JPG",
    file_size: "780 KB",
    status: "Aprovado",
    received_at: "16/09/2026",
    reviewed_by: "Felipe Nunes",
    reviewed_at: "16/09/2026",
    version: 1,
  },
  {
    id: "doc-012",
    process_id: "DHG-00142",
    client_id: "cli-004",
    unit_id: "Jardim D'Abril",
    client: "Beatriz Cardoso",
    process: "#DHG-00142",
    process_type: "CNH",
    document_type: "Comprovante de residência",
    file_name: "residencia-beatriz.pdf",
    file_type: "PDF",
    file_size: "1,1 MB",
    status: "Pendente",
    version: 0,
  },
  {
    id: "doc-013",
    process_id: "DHG-00147",
    client_id: "cli-005",
    vehicle_id: "veh-004",
    unit_id: "Jardim Conceição",
    client: "Carlos Mendes",
    process: "#DHG-00147",
    process_type: "2ª via de CRLV",
    vehicle: "Chevrolet Onix - LMN0P12",
    document_type: "RG",
    file_name: "rg-carlos.png",
    file_type: "PNG",
    file_size: "680 KB",
    status: "Recebido",
    received_at: "24/09/2026",
    version: 1,
  },
  {
    id: "doc-014",
    process_id: "DHG-00147",
    client_id: "cli-005",
    vehicle_id: "veh-004",
    unit_id: "Jardim Conceição",
    client: "Carlos Mendes",
    process: "#DHG-00147",
    process_type: "2ª via de CRLV",
    vehicle: "Chevrolet Onix - LMN0P12",
    document_type: "CRLV",
    file_name: "crlv-anterior-lmn0p12.pdf",
    file_type: "PDF",
    file_size: "1,7 MB",
    status: "Aprovado",
    received_at: "19/09/2026",
    reviewed_by: "Aline Moreira",
    reviewed_at: "20/09/2026",
    version: 1,
  },
  {
    id: "doc-015",
    process_id: "DHG-00153",
    client_id: "cli-006",
    vehicle_id: "veh-005",
    unit_id: "Jardim Conceição",
    client: "Núcleo Horizonte ME",
    process: "#DHG-00153",
    process_type: "Transferência de propriedade",
    vehicle: "Toyota Corolla - QRS3T45",
    document_type: "CPF",
    file_name: "cpf-responsavel.pdf",
    file_type: "PDF",
    file_size: "510 KB",
    status: "Aprovado",
    received_at: "15/09/2026",
    reviewed_by: "Aline Moreira",
    reviewed_at: "16/09/2026",
    version: 1,
  },
  {
    id: "doc-016",
    process_id: "DHG-00153",
    client_id: "cli-006",
    vehicle_id: "veh-005",
    unit_id: "Jardim Conceição",
    client: "Núcleo Horizonte ME",
    process: "#DHG-00153",
    process_type: "Transferência de propriedade",
    vehicle: "Toyota Corolla - QRS3T45",
    document_type: "Procuração",
    file_name: "procuracao-horizonte.pdf",
    file_type: "PDF",
    file_size: "1,0 MB",
    status: "Vencendo",
    received_at: "12/09/2026",
    expires_at: "25/09/2026",
    reviewed_by: "Aline Moreira",
    reviewed_at: "13/09/2026",
    version: 1,
  },
  {
    id: "doc-017",
    process_id: "DHG-00159",
    client_id: "cli-007",
    vehicle_id: "veh-006",
    unit_id: "Carapicuíba",
    client: "Lucas Ferreira",
    process: "#DHG-00159",
    process_type: "Regularização de débitos",
    vehicle: "Renault Kwid - UVW6X78",
    document_type: "CRLV",
    file_name: "crlv-uvw6x78.pdf",
    file_type: "PDF",
    file_size: "1,3 MB",
    status: "Aprovado",
    received_at: "14/09/2026",
    reviewed_by: "Renata Oliveira",
    reviewed_at: "15/09/2026",
    version: 1,
  },
  {
    id: "doc-018",
    process_id: "DHG-00161",
    client_id: "cli-008",
    unit_id: "Jardim Conceição",
    client: "Sofia Ramos",
    process: "#DHG-00161",
    process_type: "CNH",
    document_type: "Outros",
    file_name: "declaracao-sofia.pdf",
    file_type: "PDF",
    file_size: "430 KB",
    status: "Recebido",
    received_at: "24/09/2026",
    version: 1,
  },
];

export const documentTypes = [
  "CNH",
  "RG",
  "CPF",
  "CRLV",
  "CRV/ATPV-e",
  "Comprovante de residência",
  "Procuração",
  "Contrato",
  "Documento empresarial",
  "Outros",
];
