import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { PageHero, SectionTitle, CtaBand } from "@/components/dhg/page-elements";
const posts = [
  { category: "Veículos", title: "Transferência de veículo: entenda como a orientação profissional ajuda", text: "Cada transferência possui características próprias. Saiba por que analisar a documentação antes de iniciar o processo.", to: "/servicos/transferencia-de-veiculo" as const },
  { category: "Regularidade", title: "Licenciamento: documentos e pendências merecem atenção", text: "Uma visão geral sobre a importância de verificar o contexto documental do veículo antes de conduzir o licenciamento.", to: "/servicos/licenciamento" as const },
  { category: "Empresas", title: "Organização documental também faz parte da operação", text: "Como o acompanhamento de documentos, vencimentos e protocolos contribui para rotinas empresariais mais organizadas.", to: "/empresas" as const },
];
export const Route = createFileRoute("/conteudos")({ head: () => ({ meta: [{ title: "Conteúdos sobre Documentação | DHG" }, { name: "description", content: "Informações gerais sobre documentação veicular, regularizações, CNH e gestão documental para empresas." }, { property: "og:title", content: "Conteúdos | DHG Despachante" }, { property: "og:description", content: "Informação clara para pessoas e empresas." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ConteudosPage });
function ConteudosPage() { return <><PageHero eyebrow="Conteúdos" title="Informação para decidir com clareza." text="Orientações gerais para ajudar você a compreender processos documentais antes de falar com nossa equipe." /><section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Leituras da DHG" title="Documentação explicada sem complicação" text="Os requisitos podem variar conforme cada caso. Para uma orientação específica, fale diretamente com a equipe." /><div className="mt-14 border-t border-border">{posts.map((post, index) => <article key={post.title} className="grid gap-5 border-b border-border py-8 md:grid-cols-[80px_0.8fr_1.2fr_auto] md:items-center"><span className="text-xs font-bold text-primary">0{index + 1}</span><p className="eyebrow text-muted-foreground">{post.category}</p><div><h2 className="text-xl font-semibold text-brand-deep">{post.title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{post.text}</p></div><Link to={post.to} className="inline-flex items-center gap-2 text-sm font-semibold text-primary">Saiba mais <ArrowRight className="size-4" /></Link></article>)}</div></div></section><CtaBand /></> }
