import { createFileRoute } from "@tanstack/react-router";
import { Check } from "lucide-react";
import { PageHero, SectionTitle, CtaBand } from "@/components/dhg/page-elements";
import consultingImage from "@/assets/dhg-consultoria.jpg";
export const Route = createFileRoute("/empresas")({ head: () => ({ meta: [
  { title: "Assessoria Documental para Empresas | DHG" }, { name: "description", content: "Gestão documental, regularizações, controle de vencimentos e acompanhamento de processos para empresas." },
  { property: "og:title", content: "Soluções para Empresas | DHG" }, { property: "og:description", content: "Assessoria documental profissional para rotinas empresariais." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: EmpresasPage });
function EmpresasPage() { const items = ["Gestão de documentos e vencimentos", "Preparação de documentos e requerimentos", "Protocolização e acompanhamento de processos", "Regularizações, alvarás e licenças", "Laudos, perícias, vistorias e avaliações", "Certificações, registros e cadastros"]; return <><PageHero eyebrow="Soluções para empresas" title="Organização documental para sua operação avançar." text="Acompanhamento profissional para empresas que precisam de clareza, organização e continuidade em seus processos." image={consultingImage} /><section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-[0.75fr_1.25fr] lg:px-8"><SectionTitle eyebrow="Atuação B2B" title="Assessoria que acompanha o ritmo da empresa" text="A DHG apoia rotinas documentais e processos que exigem acompanhamento, ajudando sua equipe a manter informações e demandas organizadas." /><div className="border-t border-border">{items.map((item) => <div key={item} className="flex items-center gap-3 border-b border-border py-5 text-sm font-semibold text-brand-deep"><Check className="size-4 text-primary" />{item}</div>)}</div></div></section><section className="bg-muted/50 py-20"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Como começamos" title="Entendimento antes da execução" /><div className="mt-12 grid md:grid-cols-3">{[["01","Contexto","A equipe entende as necessidades documentais apresentadas."],["02","Orientação","Os próximos passos e documentos são organizados de acordo com o processo."],["03","Acompanhamento","A DHG conduz e acompanha as etapas aplicáveis."]].map(([n,t,d]) => <div key={n} className="border-t border-border py-7 md:border-r md:px-7 first:pl-0 last:border-r-0"><span className="text-xs font-bold text-primary">{n}</span><h3 className="mt-6 text-xl font-semibold text-brand-deep">{t}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{d}</p></div>)}</div></div></section><CtaBand title="Sua empresa precisa organizar uma demanda documental?" text="Converse com a equipe e apresente a sua necessidade." /></> }
