import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, MessageCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { CtaBand, SectionTitle, UnitSummary } from "@/components/dhg/page-elements";
import heroImage from "@/assets/dhg-atendimento.jpg";
import consultingImage from "@/assets/dhg-consultoria.jpg";
import vehicleImage from "@/assets/dhg-veiculo.jpg";
import { mainWhatsapp } from "@/lib/dhg";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "DHG Despachante | Assessoria em Carapicuíba e Osasco" },
    { name: "description", content: "Há mais de uma década, a DHG presta assessoria documental para pessoas e empresas em Carapicuíba e Osasco." },
    { property: "og:title", content: "DHG Despachante e Assessoria" },
    { property: "og:description", content: "Documentação resolvida. Sem complicação." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ], scripts: [{ type: "application/ld+json", children: JSON.stringify({ "@context": "https://schema.org", "@type": "ProfessionalService", name: "DHG Despachante e Assessoria", foundingDate: "2012", areaServed: ["Carapicuíba", "Osasco"], description: "Assessoria documental para pessoas e empresas." }) }] }),
  component: HomePage,
});

function HomePage() {
  return <>
    <section className="relative min-h-[680px] overflow-hidden bg-brand-deep text-primary-foreground lg:min-h-[760px]">
      <img src={heroImage} alt="Atendimento profissional de assessoria documental DHG" className="absolute inset-0 h-full w-full object-cover object-[62%_center]" width="1536" height="1024" fetchPriority="high" />
      <div className="absolute inset-0 bg-brand-hero" />
      <div className="relative mx-auto flex min-h-[680px] max-w-7xl items-end px-5 pb-20 pt-24 lg:min-h-[760px] lg:px-8 lg:pb-24">
        <div className="max-w-3xl"><p className="eyebrow text-primary-foreground/65">Assessoria documental desde 2012</p><h1 className="mt-5 max-w-2xl text-5xl font-semibold leading-[1.02] sm:text-6xl lg:text-7xl">Documentação resolvida.<br />Sem complicação.</h1><p className="mt-7 max-w-2xl text-base leading-7 text-primary-foreground/75 sm:text-lg">Há mais de uma década, a DHG presta assessoria documental para pessoas e empresas, cuidando dos processos para você ganhar tempo e tranquilidade.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg" className="h-12 bg-primary-foreground px-6 text-brand-deep shadow-none hover:bg-primary-foreground/90"><a href={mainWhatsapp} target="_blank" rel="noreferrer"><MessageCircle /> Falar com um especialista</a></Button><Button asChild size="lg" variant="outline" className="h-12 border-primary-foreground/40 bg-transparent px-6 text-primary-foreground shadow-none hover:bg-primary-foreground/10 hover:text-primary-foreground"><Link to="/sobre">Conhecer a DHG <ArrowRight /></Link></Button></div></div>
      </div>
    </section>

    <section className="bg-brand-blue py-12 text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1fr_1.4fr] lg:px-8"><h2 className="text-3xl font-semibold">Experiência que faz diferença.</h2><div className="grid grid-cols-2 gap-y-7 sm:grid-cols-4">{[["2012", "Atuação desde"], ["03", "Unidades"], ["PF", "Pessoa Física"], ["PJ", "Pessoa Jurídica"]].map(([value, label]) => <div key={value} className="border-l border-primary-foreground/25 pl-5"><strong className="text-2xl">{value}</strong><span className="mt-1 block text-xs text-primary-foreground/65">{label}</span></div>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-2 lg:items-center lg:px-8"><div className="relative"><img src={consultingImage} alt="Consultoria documental DHG" className="aspect-[4/3] w-full object-cover" width="1536" height="1024" loading="lazy" /><span className="absolute bottom-0 left-0 bg-brand-deep px-6 py-4 text-sm font-semibold text-primary-foreground">Desde 2012</span></div><div className="lg:pl-12"><SectionTitle eyebrow="Sobre a DHG" title="Mais do que despachante. Assessoria para resolver." text="A DHG nasceu para facilitar processos documentais. Hoje, combina experiência operacional, atendimento próximo e orientação transparente para pessoas e empresas." /><Link to="/sobre" className="mt-8 inline-flex items-center gap-2 text-sm font-semibold text-primary">Conheça nossa história <ArrowRight className="size-4" /></Link></div></div></section>

    <section className="bg-muted/50 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Serviços" title="Soluções para cada necessidade" text="Uma estrutura de atendimento preparada para diferentes momentos da vida documental." /><div className="mt-14 grid border-t border-border lg:grid-cols-2">{[
      ["01", "Documentação Veicular", "Emplacamento, transferências, licenciamento e atualizações.", "/servicos/documentacao-veicular"],
      ["02", "Débitos e Regularizações", "Orientação para pendências, taxas e regularização.", "/servicos/debitos-e-regularizacoes"],
      ["03", "CNH e Documentação", "Renovação, segunda via e serviços relacionados.", "/servicos/cnh"],
      ["04", "Soluções para Empresas", "Gestão documental e acompanhamento de processos.", "/empresas"],
    ].map(([num, title, text, to], index) => <Link key={title} to={to as "/empresas"} className={`group border-b border-border py-8 lg:px-8 ${index % 2 === 0 ? "lg:border-r lg:pl-0" : ""}`}><span className="text-xs font-bold text-primary">{num}</span><h3 className="mt-5 text-2xl font-semibold text-brand-deep">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p><ArrowRight className="mt-6 size-5 text-primary transition-transform group-hover:translate-x-1" /></Link>)}</div><Button asChild variant="outline" className="mt-9 h-11 border-brand-deep/20 text-brand-deep"><Link to="/servicos">Ver todos os serviços <ArrowRight /></Link></Button></div></section>

    <section className="grid lg:grid-cols-2"><div className="min-h-[460px]"><img src={vehicleImage} alt="Assessoria para documentação veicular" className="h-full w-full object-cover" width="1536" height="1024" loading="lazy" /></div><div className="bg-brand-deep px-5 py-16 text-primary-foreground sm:px-12 lg:flex lg:flex-col lg:justify-center lg:px-16"><p className="eyebrow text-primary-foreground/60">Para pessoas</p><h2 className="mt-4 text-4xl font-semibold">Seu veículo. Sua tranquilidade.</h2><p className="mt-6 max-w-xl leading-7 text-primary-foreground/70">Conte com orientação para documentação, transferências, licenciamento, pendências e serviços relacionados à CNH.</p><Button asChild className="mt-8 w-fit bg-whatsapp text-primary-foreground hover:bg-whatsapp/90"><a href={mainWhatsapp} target="_blank" rel="noreferrer"><MessageCircle /> Falar sobre meu veículo</a></Button></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-12 px-5 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><SectionTitle eyebrow="Para empresas" title="Assessoria documental para empresas" text="Suporte profissional para rotinas que exigem organização, acompanhamento e clareza." /><div className="grid gap-px bg-border sm:grid-cols-2">{["Gestão documental", "Processos", "Regularizações", "Documentação veicular", "Controle de vencimentos", "Protocolização"].map((item) => <div key={item} className="flex items-center gap-3 bg-background p-5 text-sm font-semibold text-brand-deep"><Check className="size-4 text-primary" />{item}</div>)}<Link to="/empresas" className="flex items-center gap-2 bg-brand-blue p-5 text-sm font-semibold text-primary-foreground sm:col-span-2">Conhecer soluções para empresas <ArrowRight className="size-4" /></Link></div></div></section>

    <section className="bg-muted/50 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><SectionTitle eyebrow="Atendimento claro" title="Como funciona" /><ol className="mt-12 grid border-y border-border md:grid-cols-5">{["Entre em contato", "Explique o que precisa", "Receba orientação", "A DHG conduz o processo", "Acompanhe o andamento"].map((step, index) => <li key={step} className="border-b border-border py-6 md:border-b-0 md:border-r md:px-5 first:pl-0 last:border-r-0"><span className="text-xs font-bold text-primary">0{index + 1}</span><p className="mt-6 text-sm font-semibold leading-6 text-brand-deep">{step}</p></li>)}</ol></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionTitle eyebrow="Presença local" title="Onde estamos" text="Três unidades para atender você em Carapicuíba e Osasco." /><Link to="/unidades" className="inline-flex items-center gap-2 text-sm font-semibold text-primary">Ver todas as unidades <ArrowRight className="size-4" /></Link></div><div className="mt-12"><UnitSummary unitKey="carapicuiba" /><UnitSummary unitKey="osasco-jardim-dabril" /><UnitSummary unitKey="osasco-jardim-conceicao" /></div></div></section>

    <section className="bg-brand-deep py-16 text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><p className="eyebrow text-primary-foreground/60">Avaliações no Google</p><h2 className="mt-4 text-3xl font-semibold">Confiança construída no atendimento.</h2></div><div className="grid gap-6 sm:grid-cols-3">{["Carapicuíba", "Osasco · Conceição", "Osasco · Jd. D'Abril"].map((name) => <div key={name} className="border-l border-primary-foreground/25 pl-5"><span className="text-xl text-primary-foreground" aria-label="5 estrelas">★★★★★</span><p className="mt-3 font-semibold">Avaliação 5,0</p><p className="mt-1 text-xs text-primary-foreground/60">{name}</p></div>)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-8"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><SectionTitle eyebrow="Conteúdos" title="Informação para decidir com clareza" text="Orientações gerais sobre processos documentais para pessoas e empresas." /><Link to="/conteudos" className="inline-flex items-center gap-2 text-sm font-semibold text-primary">Ver todos os conteúdos <ArrowRight className="size-4" /></Link></div><div className="mt-12 grid border-t border-border md:grid-cols-3">{["Transferência de veículo: entenda o processo", "Licenciamento: o que observar", "Organização documental para empresas"].map((title, index) => <article key={title} className="border-b border-border py-7 md:border-r md:px-7 first:pl-0 last:border-r-0"><span className="text-xs font-bold text-primary">0{index + 1}</span><h3 className="mt-8 text-xl font-semibold leading-7 text-brand-deep">{title}</h3><Link to="/conteudos" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-primary">Ler conteúdo <ArrowRight className="size-4" /></Link></article>)}</div></div></section>
    <CtaBand />
  </>;
}
