import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight } from "lucide-react";
import { PageHero, SectionTitle, CtaBand } from "@/components/dhg/page-elements";
import consultingImage from "@/assets/dhg-consultoria.jpg";

export const Route = createFileRoute("/sobre")({ head: () => ({ meta: [
  { title: "Sobre a DHG | Experiência desde 2012" }, { name: "description", content: "Conheça a trajetória da DHG e sua atuação em assessoria documental para pessoas e empresas desde 2012." },
  { property: "og:title", content: "Sobre a DHG Despachante" }, { property: "og:description", content: "Experiência, atendimento e transparência em assessoria documental." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
] }), component: SobrePage });
function SobrePage() { return <><PageHero eyebrow="A DHG" title="Experiência para tornar processos mais simples." text="Desde 2012, a DHG atua com assessoria documental para pessoas e empresas em Carapicuíba e Osasco." image={consultingImage} /><section className="py-20 sm:py-28"><div className="mx-auto grid max-w-7xl gap-14 px-5 lg:grid-cols-[0.7fr_1.3fr] lg:px-8"><SectionTitle eyebrow="Nossa história" title="Mais do que despachante. Assessoria para resolver." /><div className="space-y-6 text-lg leading-8 text-muted-foreground"><p>A DHG nasceu com um propósito claro: facilitar a vida de quem precisa lidar com documentação, veículos e processos junto a órgãos públicos.</p><p>Ao longo de mais de uma década, a empresa desenvolveu experiência operacional para entender cada necessidade, orientar sobre as etapas e acompanhar processos com organização.</p><p>Hoje, atende pessoas e empresas por meio de três unidades físicas, mantendo a proximidade no atendimento e a transparência nas informações.</p></div></div></section><section className="bg-brand-deep py-20 text-primary-foreground"><div className="mx-auto max-w-7xl px-5 lg:px-8"><p className="eyebrow text-primary-foreground/60">O que orienta nosso trabalho</p><div className="mt-10 grid border-t border-primary-foreground/20 md:grid-cols-3">{[["01", "Atendimento", "Escuta atenta para compreender o que cada pessoa ou empresa precisa."], ["02", "Transparência", "Informações claras sobre documentos, etapas e particularidades de cada processo."], ["03", "Experiência", "Conhecimento construído na prática desde 2012."]].map(([n,t,d]) => <div key={n} className="border-b border-primary-foreground/20 py-8 md:border-r md:px-8 first:pl-0 last:border-r-0"><span className="text-xs text-primary-foreground/50">{n}</span><h2 className="mt-8 text-2xl font-semibold">{t}</h2><p className="mt-4 text-sm leading-6 text-primary-foreground/65">{d}</p></div>)}</div></div></section><section className="py-20 sm:py-28"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 px-5 md:flex-row md:items-center lg:px-8"><SectionTitle eyebrow="Presença local" title="Três unidades. Uma só forma de atender." text="A DHG está presente em Carapicuíba e Osasco, atendendo necessidades de pessoas e empresas." /><Link to="/unidades" className="inline-flex shrink-0 items-center gap-2 font-semibold text-primary">Conheça nossas unidades <ArrowRight className="size-4" /></Link></div></section><CtaBand /></> }
