CREATE TYPE public.app_role AS ENUM ('admin','staff');
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL, role public.app_role NOT NULL, UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.has_role(_user_id uuid, _role public.app_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT EXISTS (SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE FUNCTION public.is_staff(_user_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT public.has_role(_user_id,'admin') OR public.has_role(_user_id,'staff') $$;
GRANT EXECUTE ON FUNCTION public.has_role(uuid,public.app_role) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_staff(uuid) TO authenticated;
CREATE POLICY "Staff view roles" ON public.user_roles FOR SELECT TO authenticated USING (public.is_staff(auth.uid()));
CREATE TABLE public.dhg_clients (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, person_type text NOT NULL DEFAULT 'PF' CHECK (person_type IN ('PF','PJ')), cpf text, cnpj text, rg text, cnh text, phone text, email text, unit text NOT NULL, notes text, created_by uuid NOT NULL DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.dhg_clients TO authenticated; GRANT ALL ON public.dhg_clients TO service_role;
ALTER TABLE public.dhg_clients ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff read clients" ON public.dhg_clients FOR SELECT TO authenticated USING (public.is_staff(auth.uid()));
CREATE POLICY "Staff add clients" ON public.dhg_clients FOR INSERT TO authenticated WITH CHECK (public.is_staff(auth.uid()) AND created_by=auth.uid());
CREATE POLICY "Staff edit clients" ON public.dhg_clients FOR UPDATE TO authenticated USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));
CREATE POLICY "Admin delete clients" ON public.dhg_clients FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin'));
CREATE TABLE public.dhg_processes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), client_id uuid NOT NULL REFERENCES public.dhg_clients(id) ON DELETE RESTRICT, unit text NOT NULL, service text NOT NULL, stage text NOT NULL DEFAULT 'Aberto' CHECK (stage IN ('Aberto','Documentos pendentes','Protocolado no órgão','Aguardando análise','Pendência a resolver','Concluído','Cancelado')), plate text, protocol text, deadline date, notes text, created_by uuid NOT NULL DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.dhg_processes TO authenticated; GRANT ALL ON public.dhg_processes TO service_role;
ALTER TABLE public.dhg_processes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff read processes" ON public.dhg_processes FOR SELECT TO authenticated USING (public.is_staff(auth.uid()));
CREATE POLICY "Staff add processes" ON public.dhg_processes FOR INSERT TO authenticated WITH CHECK (public.is_staff(auth.uid()) AND created_by=auth.uid());
CREATE POLICY "Staff edit processes" ON public.dhg_processes FOR UPDATE TO authenticated USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));
CREATE POLICY "Admin delete processes" ON public.dhg_processes FOR DELETE TO authenticated USING (public.has_role(auth.uid(),'admin'));
CREATE TABLE public.dhg_documents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), client_id uuid NOT NULL REFERENCES public.dhg_clients(id) ON DELETE CASCADE, process_id uuid REFERENCES public.dhg_processes(id) ON DELETE SET NULL, category text NOT NULL, file_name text NOT NULL, storage_path text NOT NULL UNIQUE, mime_type text, size_bytes bigint, created_by uuid NOT NULL DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.dhg_documents TO authenticated; GRANT ALL ON public.dhg_documents TO service_role;
ALTER TABLE public.dhg_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff read documents" ON public.dhg_documents FOR SELECT TO authenticated USING (public.is_staff(auth.uid()));
CREATE POLICY "Staff add documents" ON public.dhg_documents FOR INSERT TO authenticated WITH CHECK (public.is_staff(auth.uid()) AND created_by=auth.uid());
CREATE POLICY "Staff edit documents" ON public.dhg_documents FOR UPDATE TO authenticated USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()));
CREATE POLICY "Staff delete documents" ON public.dhg_documents FOR DELETE TO authenticated USING (public.is_staff(auth.uid()));
CREATE INDEX dhg_clients_name_idx ON public.dhg_clients(name);
CREATE INDEX dhg_processes_client_idx ON public.dhg_processes(client_id);
CREATE INDEX dhg_documents_client_idx ON public.dhg_documents(client_id);
CREATE POLICY "Staff upload files" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id='dhg-documents' AND public.is_staff(auth.uid()) AND (storage.foldername(name))[1] = auth.uid()::text);
CREATE POLICY "Staff read files" ON storage.objects FOR SELECT TO authenticated USING (bucket_id='dhg-documents' AND public.is_staff(auth.uid()));
CREATE POLICY "Staff remove files" ON storage.objects FOR DELETE TO authenticated USING (bucket_id='dhg-documents' AND public.is_staff(auth.uid()));