/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as UnidadesRouteImport } from './routes/unidades'
import { Route as ServicosCnhRouteImport } from './routes/servicos.cnh'
import { Route as ServicosDebitosERegularizacoesRouteImport } from './routes/servicos.debitos-e-regularizacoes'
import { Route as ServicosDocumentacaoVeicularRouteImport } from './routes/servicos.documentacao-veicular'
import { Route as ServicosLicenciamentoRouteImport } from './routes/servicos.licenciamento'
import { Route as ServicosTransferenciaDeVeiculoRouteImport } from './routes/servicos.transferencia-de-veiculo'
import { Route as UnidadesCarapicuibaRouteImport } from './routes/unidades.carapicuiba'
import { Route as UnidadesOsascoJardimConceicaoRouteImport } from './routes/unidades.osasco-jardim-conceicao'
import { Route as UnidadesOsascoJardimDabrilRouteImport } from './routes/unidades.osasco-jardim-dabril'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const UnidadesRoute = UnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosCnhRoute = ServicosCnhRouteImport.update({
  id: '/cnh',
  path: '/cnh',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosDebitosERegularizacoesRoute =
  ServicosDebitosERegularizacoesRouteImport.update({
    id: '/debitos-e-regularizacoes',
    path: '/debitos-e-regularizacoes',
    getParentRoute: () => ServicosRoute,
  } as any)
const ServicosDocumentacaoVeicularRoute =
  ServicosDocumentacaoVeicularRouteImport.update({
    id: '/documentacao-veicular',
    path: '/documentacao-veicular',
    getParentRoute: () => ServicosRoute,
  } as any)
const ServicosLicenciamentoRoute = ServicosLicenciamentoRouteImport.update({
  id: '/licenciamento',
  path: '/licenciamento',
  getParentRoute: () => ServicosRoute,
} as any)
const ServicosTransferenciaDeVeiculoRoute =
  ServicosTransferenciaDeVeiculoRouteImport.update({
    id: '/transferencia-de-veiculo',
    path: '/transferencia-de-veiculo',
    getParentRoute: () => ServicosRoute,
  } as any)
const UnidadesCarapicuibaRoute = UnidadesCarapicuibaRouteImport.update({
  id: '/carapicuiba',
  path: '/carapicuiba',
  getParentRoute: () => UnidadesRoute,
} as any)
const UnidadesOsascoJardimConceicaoRoute =
  UnidadesOsascoJardimConceicaoRouteImport.update({
    id: '/osasco-jardim-conceicao',
    path: '/osasco-jardim-conceicao',
    getParentRoute: () => UnidadesRoute,
  } as any)
const UnidadesOsascoJardimDabrilRoute =
  UnidadesOsascoJardimDabrilRouteImport.update({
    id: '/osasco-jardim-dabril',
    path: '/osasco-jardim-dabril',
    getParentRoute: () => UnidadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/unidades': typeof UnidadesRouteWithChildren
  '/servicos/cnh': typeof ServicosCnhRoute
  '/servicos/debitos-e-regularizacoes': typeof ServicosDebitosERegularizacoesRoute
  '/servicos/documentacao-veicular': typeof ServicosDocumentacaoVeicularRoute
  '/servicos/licenciamento': typeof ServicosLicenciamentoRoute
  '/servicos/transferencia-de-veiculo': typeof ServicosTransferenciaDeVeiculoRoute
  '/unidades/carapicuiba': typeof UnidadesCarapicuibaRoute
  '/unidades/osasco-jardim-conceicao': typeof UnidadesOsascoJardimConceicaoRoute
  '/unidades/osasco-jardim-dabril': typeof UnidadesOsascoJardimDabrilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/unidades': typeof UnidadesRouteWithChildren
  '/servicos/cnh': typeof ServicosCnhRoute
  '/servicos/debitos-e-regularizacoes': typeof ServicosDebitosERegularizacoesRoute
  '/servicos/documentacao-veicular': typeof ServicosDocumentacaoVeicularRoute
  '/servicos/licenciamento': typeof ServicosLicenciamentoRoute
  '/servicos/transferencia-de-veiculo': typeof ServicosTransferenciaDeVeiculoRoute
  '/unidades/carapicuiba': typeof UnidadesCarapicuibaRoute
  '/unidades/osasco-jardim-conceicao': typeof UnidadesOsascoJardimConceicaoRoute
  '/unidades/osasco-jardim-dabril': typeof UnidadesOsascoJardimDabrilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/empresas': typeof EmpresasRoute
  '/servicos': typeof ServicosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/unidades': typeof UnidadesRouteWithChildren
  '/servicos/cnh': typeof ServicosCnhRoute
  '/servicos/debitos-e-regularizacoes': typeof ServicosDebitosERegularizacoesRoute
  '/servicos/documentacao-veicular': typeof ServicosDocumentacaoVeicularRoute
  '/servicos/licenciamento': typeof ServicosLicenciamentoRoute
  '/servicos/transferencia-de-veiculo': typeof ServicosTransferenciaDeVeiculoRoute
  '/unidades/carapicuiba': typeof UnidadesCarapicuibaRoute
  '/unidades/osasco-jardim-conceicao': typeof UnidadesOsascoJardimConceicaoRoute
  '/unidades/osasco-jardim-dabril': typeof UnidadesOsascoJardimDabrilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/empresas'
    | '/servicos'
    | '/sobre'
    | '/unidades'
    | '/servicos/cnh'
    | '/servicos/debitos-e-regularizacoes'
    | '/servicos/documentacao-veicular'
    | '/servicos/licenciamento'
    | '/servicos/transferencia-de-veiculo'
    | '/unidades/carapicuiba'
    | '/unidades/osasco-jardim-conceicao'
    | '/unidades/osasco-jardim-dabril'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/empresas'
    | '/servicos'
    | '/sobre'
    | '/unidades'
    | '/servicos/cnh'
    | '/servicos/debitos-e-regularizacoes'
    | '/servicos/documentacao-veicular'
    | '/servicos/licenciamento'
    | '/servicos/transferencia-de-veiculo'
    | '/unidades/carapicuiba'
    | '/unidades/osasco-jardim-conceicao'
    | '/unidades/osasco-jardim-dabril'
  id:
    | '__root__'
    | '/'
    | '/empresas'
    | '/servicos'
    | '/sobre'
    | '/unidades'
    | '/servicos/cnh'
    | '/servicos/debitos-e-regularizacoes'
    | '/servicos/documentacao-veicular'
    | '/servicos/licenciamento'
    | '/servicos/transferencia-de-veiculo'
    | '/unidades/carapicuiba'
    | '/unidades/osasco-jardim-conceicao'
    | '/unidades/osasco-jardim-dabril'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EmpresasRoute: typeof EmpresasRoute
  ServicosRoute: typeof ServicosRouteWithChildren
  SobreRoute: typeof SobreRoute
  UnidadesRoute: typeof UnidadesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unidades': {
      id: '/unidades'
      path: '/unidades'
      fullPath: '/unidades'
      preLoaderRoute: typeof UnidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/cnh': {
      id: '/servicos/cnh'
      path: '/cnh'
      fullPath: '/servicos/cnh'
      preLoaderRoute: typeof ServicosCnhRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/debitos-e-regularizacoes': {
      id: '/servicos/debitos-e-regularizacoes'
      path: '/debitos-e-regularizacoes'
      fullPath: '/servicos/debitos-e-regularizacoes'
      preLoaderRoute: typeof ServicosDebitosERegularizacoesRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/documentacao-veicular': {
      id: '/servicos/documentacao-veicular'
      path: '/documentacao-veicular'
      fullPath: '/servicos/documentacao-veicular'
      preLoaderRoute: typeof ServicosDocumentacaoVeicularRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/licenciamento': {
      id: '/servicos/licenciamento'
      path: '/licenciamento'
      fullPath: '/servicos/licenciamento'
      preLoaderRoute: typeof ServicosLicenciamentoRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/servicos/transferencia-de-veiculo': {
      id: '/servicos/transferencia-de-veiculo'
      path: '/transferencia-de-veiculo'
      fullPath: '/servicos/transferencia-de-veiculo'
      preLoaderRoute: typeof ServicosTransferenciaDeVeiculoRouteImport
      parentRoute: typeof ServicosRoute
    }
    '/unidades/carapicuiba': {
      id: '/unidades/carapicuiba'
      path: '/carapicuiba'
      fullPath: '/unidades/carapicuiba'
      preLoaderRoute: typeof UnidadesCarapicuibaRouteImport
      parentRoute: typeof UnidadesRoute
    }
    '/unidades/osasco-jardim-conceicao': {
      id: '/unidades/osasco-jardim-conceicao'
      path: '/osasco-jardim-conceicao'
      fullPath: '/unidades/osasco-jardim-conceicao'
      preLoaderRoute: typeof UnidadesOsascoJardimConceicaoRouteImport
      parentRoute: typeof UnidadesRoute
    }
    '/unidades/osasco-jardim-dabril': {
      id: '/unidades/osasco-jardim-dabril'
      path: '/osasco-jardim-dabril'
      fullPath: '/unidades/osasco-jardim-dabril'
      preLoaderRoute: typeof UnidadesOsascoJardimDabrilRouteImport
      parentRoute: typeof UnidadesRoute
    }
  }
}

interface ServicosRouteChildren {
  ServicosCnhRoute: typeof ServicosCnhRoute
  ServicosDebitosERegularizacoesRoute: typeof ServicosDebitosERegularizacoesRoute
  ServicosDocumentacaoVeicularRoute: typeof ServicosDocumentacaoVeicularRoute
  ServicosLicenciamentoRoute: typeof ServicosLicenciamentoRoute
  ServicosTransferenciaDeVeiculoRoute: typeof ServicosTransferenciaDeVeiculoRoute
}

const ServicosRouteChildren: ServicosRouteChildren = {
  ServicosCnhRoute: ServicosCnhRoute,
  ServicosDebitosERegularizacoesRoute: ServicosDebitosERegularizacoesRoute,
  ServicosDocumentacaoVeicularRoute: ServicosDocumentacaoVeicularRoute,
  ServicosLicenciamentoRoute: ServicosLicenciamentoRoute,
  ServicosTransferenciaDeVeiculoRoute: ServicosTransferenciaDeVeiculoRoute,
}

const ServicosRouteWithChildren = ServicosRoute._addFileChildren(
  ServicosRouteChildren,
)

interface UnidadesRouteChildren {
  UnidadesCarapicuibaRoute: typeof UnidadesCarapicuibaRoute
  UnidadesOsascoJardimConceicaoRoute: typeof UnidadesOsascoJardimConceicaoRoute
  UnidadesOsascoJardimDabrilRoute: typeof UnidadesOsascoJardimDabrilRoute
}

const UnidadesRouteChildren: UnidadesRouteChildren = {
  UnidadesCarapicuibaRoute: UnidadesCarapicuibaRoute,
  UnidadesOsascoJardimConceicaoRoute: UnidadesOsascoJardimConceicaoRoute,
  UnidadesOsascoJardimDabrilRoute: UnidadesOsascoJardimDabrilRoute,
}

const UnidadesRouteWithChildren = UnidadesRoute._addFileChildren(
  UnidadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EmpresasRoute: EmpresasRoute,
  ServicosRoute: ServicosRouteWithChildren,
  SobreRoute: SobreRoute,
  UnidadesRoute: UnidadesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
